service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-2

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: lambda-github-new
    handler: lambda.handler
    description: lambda-github
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"